FROM python:3.12

RUN pip install flask

WORKDIR /app

COPY TodoListManagement.py /app
COPY templates/ templates/
COPY static/ static/

EXPOSE 5000

ENTRYPOINT ["python"]
CMD ["TodoListManagement.py"]